site_name: Red Team Techniques
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: cyan
  features:
    - navigation.tabs
    - navigation.indexes
  extra:
    social:
      - icon: fontawesome/brands/twitter 
        link: https://twitter.com/csenox1
      - icon: fontawesome/brands/twitter 
        link: https://twitter.com/d4rckh
extra:
  analytics:
    provider: google
    property: G-Y39JH8Q7SV